[package]
name = "memflow-win32-ffi"
version = "0.1.0"
authors = ["Aurimas Blažulionis <0x60@pm.me>"]
edition = "2018"
build = "build.rs"

[lib]
name = "memflow_win32_ffi"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
memflow-win32 = { path = "../memflow-win32" }
memflow-core = { path = "../memflow-core" }
memflow-core-ffi = { path = "../memflow-core-ffi" }

[build-dependencies]
cbindgen = "0.14.4"
