[workspace]
members = [
    "flow-core",
    "flow-core/address",
    "flow-core/arch",
    "flow-core/mem",
    "flow-va",
    "flow-cli",
    "flow-qemu",
    "flow-qemu/bridge",
    "flow-win32",
]
default-members = [
    "flow-core",
    "flow-core/address",
    "flow-core/arch",
    "flow-core/mem",
    "flow-va",
    "flow-cli",
    "flow-qemu",
    "flow-qemu/bridge",
    "flow-win32",
]