[workspace]
members = [
    "flow-core",
    "flow-cli",
    "flow-qemu",
    "flow-qemu/bridge",
    "flow-win32",
]
default-members = [
    "flow-core",
    "flow-cli",
    "flow-qemu",
    "flow-qemu/bridge",
    "flow-win32",
]