[package]
name = "flow-cli"
version = "0.1.0"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.*"
flow-core = { path = "../flow-core" }
flow-qemu = { path = "../flow-qemu" }