[package]
name = "flow-win32"
version = "0.1.0"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[dependencies]
address = { path = "../flow-core/address" }
arch = { path = "../flow-core/arch" }
mem = { path = "../flow-core/mem" }
byteorder = "1.*"
num = "0.*"
goblin = "0.0.*"
